version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: '08:00'
  - package-ecosystem: "gitsubmodule"
    directory: "/themes/hugo-coder-forked"
    schedule:
      interval: "weekly"
      time: '08:00'
